base/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from core import views
from accounts import views as e




urlpatterns = [

    path('', e.authenticationUser, name='login'),
    path('home/', views.home, name='home'),
    path('example/', views.example, name='example'),
    path('auditoria/', views.auditoria, name='auditoria'),
    path('', include('fiscalizacao.urls')),
    # modificado
    path('', include('monitoramento.urls')),
    #
    path('denuncias/', views.denuncias, name='denuncias'),
    path('fraudes/', views.fraudes, name='fraudes'),
    path('lista_negativa_agr/', views.lista_negativa_agr, name='lista_negativa_agr'),
    path('dossies/', views.dossies, name='dossies'),
    path('admin/', admin.site.urls),
    path('', include('cadastro.urls')),
    path('', include('accounts.urls'))
]

cadastro/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('entidade/home', views.index, name='entidade/home'),
    path('entidade/cadastro', views.novaEntidade, name='entidade/cadastro'),

    path(r'^entidade/detalhes/(?P<pk>\d+)/', views.detalhes, name='entidade/detalhes'),

    path('entidade/lista',views.listaEntidades, name='entidade/lista'),
    url(r'^entidade/altera/(?P<pk>\d+)/',views.altera, name='entidade/altera'),

    path('entidade/gravaentidade',views.gravaEntidade, name='entidade/gravaentidade'),

    path('bbb', views.ajax, name='ajax'),



]

cadastro/models.py
from django.db import models

# Create your models here.
from datetime import datetime


# Create your models here.

class TipoEntidade(models.Model):

    tipo_descricao = models.CharField(max_length=255, blank=False, null=False)

    objects = models.Manager()

    def __str__(self):
        return self.tipo_descricao

class Entidade(models.Model):

    tipo_entidade = models.ForeignKey(TipoEntidade, on_delete=models.CASCADE)

    razao_social = models.CharField("Razão Social", max_length=255, blank=False, null=True)

    nome_entidade= models.CharField(max_length=255, blank=False, null=True)

    cnpj_entidade = models.CharField(max_length=14, null=False, blank=False)

    telefone_entidade = models.CharField(max_length=50, null=True)

    email_entidade = models.CharField(max_length=255, null=True)

    dt_credenciamento = models.DateTimeField(default=datetime.now, null=True)

    ativa = models.BooleanField(default=True, null=False)

    objects = models.Manager()

    def __str__(self):
        return self.nome_entidade


class EstadoIbge(models.Model):

    descricao_estado = models.CharField(
        max_length=255
    )

    uf = models.CharField(
        max_length = 3
    )

    objects = models.Manager()

    def __str__(self):
        return self.uf



class MunicipioIbge(models.Model):

    estado_ibge = models.ForeignKey(EstadoIbge, on_delete=models.CASCADE, verbose_name="UF")

    descricao_mun_ibge = models.CharField(max_length=255)

    objects = models.Manager()

    def __str__(self):
        return self.descricao_mun_ibge






class Endereco(models.Model):

    municipio_ibge = models.ForeignKey(MunicipioIbge, on_delete=models.CASCADE, verbose_name="Município")

    cep = models.CharField(max_length=8,null=True)

    logradouro = models.CharField(max_length=255,null=True)

    bairro = models.CharField(max_length=255,null=True)

    numero = models.CharField(max_length=255, null=True)

    complemento = models.CharField(max_length=255,null=True, blank=True)

    latitude = models.CharField(max_length=255, null=True)

    longitude = models.CharField(max_length=255, null=True)

    objects = models.Manager()





class EntidadeEndereco(models.Model):
    entidade = models.ForeignKey(Entidade, on_delete=models.CASCADE)

    endereco = models.ForeignKey(Endereco, on_delete=models.CASCADE)

    tipo_endereco = models.CharField(max_length=255, null=True)

    dt_criacao = models.DateTimeField(default=datetime.now, null=True)

    dt_extincao = models.DateTimeField(null=True)

    objects = models.Manager()

    def __str__(self):
        return self.tipo_endereco





class Oid(models.Model):

    entidade = models.ForeignKey(Entidade, on_delete=models.CASCADE)

    descricao_oid = models.CharField(max_length=255, null=True)

    oid = models.CharField(max_length=255, null=False)

    objects = models.Manager()

    def __str__(self):
        return self.descricao_oid


class TipoPessoa(models.Model):
    descricao_pessoa = models.CharField(max_length=255, blank=False, null=False)

    objects = models.Manager()

    def __str__(self):
        return self.descricao_pessoa


class PessoaFisica(models.Model):

    nome_pessoa = models.CharField(max_length=255, null=True, blank=False)

    cpf_pessoa = models.CharField(max_length=11, null=True)

    tipo_pessoa = models.ForeignKey(TipoPessoa, on_delete=models.CASCADE)

    objects = models.Manager()



class EntidadePessoa(models.Model):

    entidade = models.ForeignKey(Entidade, on_delete=models.CASCADE)

    pessoa = models.ForeignKey(PessoaFisica, on_delete=models.CASCADE)

    telefone_pessoa = models.CharField(max_length=50, null=True)

    email_pessoa = models.CharField(max_length=255, null=True)

    dt_criacao = models.DateTimeField(default=datetime.now, null=True)

    dt_extincao = models.DateTimeField(null=True)

    objects = models.Manager()




#class EntidadeSei(models.Model):



class TipoProcesso(models.Model):
    descricao_processo = models.CharField(max_length=255, blank=False, null=False)

    objects = models.Manager()

    def __str__(self):
        return self.descricao_processo


class Sei(models.Model):

    entidades = models.ManyToManyField(Entidade)

    descricao = models.TextField(null=True)

    nro_processo = models.CharField(max_length=255)

    dt_inclusao = models.DateTimeField(default=datetime.now, null=True)

    tipo_processo = models.ForeignKey(TipoProcesso, on_delete=models.CASCADE)

    objects = models.Manager()




class EntidadeVinculada(models.Model):

    entidade_propria = models.ForeignKey(Entidade, related_name='entidade_propria', on_delete=models.CASCADE, verbose_name="Entidade pai")

    entidade_filha = models.ForeignKey(Entidade, related_name='entidade_filha', on_delete=models.CASCADE, verbose_name="Entidade filha")

    dt_vinculacao = models.DateTimeField(null=True)

    dt_extincao = models.DateTimeField(null=True)

    objects = models.Manager()


class Situacao(models.Model):

    descricao_situacao = models.CharField(
        max_length=255
    )

    objects = models.Manager()

    def __str__(self):
        return self.descricao_situacao




class EntidadeVinSituacao(models.Model):

    entidade_vinculada = models.ForeignKey(EntidadeVinculada, on_delete=models.CASCADE)

    situacao = models.ForeignKey(Situacao, on_delete=models.CASCADE)

    dt_criacao = models.DateTimeField(null=True)

    dt_extincao = models.DateTimeField(null=True)

    objects = models.Manager()

cadastro/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse

from datetime import date
from django.contrib.auth.decorators import login_required
import urllib.request, json


from . import models
from . import  forms
from . import  functions

from . import models
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse


from . import models

from . import  forms

from . import models

# Create your views here.


def novaEntidade(request):
    print("novo")
    formEntidade = forms.EntidadeForm(request.POST or None)
    formEntVin = forms.EntidadeVinculadaForm(request.POST or None)
    formEntidadeVinSit = forms.EntidadeVinSituacaoForm(request.POST or None)

    context = {
        'form_entidade': formEntidade,
        'form_ent_vin': formEntVin,
        'form_ent_vin_sit': formEntidadeVinSit,
        'listTipoProcesso': models.TipoProcesso.objects.all,
        'list_estados_ibge': models.EstadoIbge.objects.all,
        'list_mun_ibge': models.MunicipioIbge.objects.all,
        'entidade_active': True,
        'tipo_formulario': "cadastro",
        'list_tipo_pessoa': models.TipoPessoa.objects.all,
    }


    if 'id_entidade_altera' in request.session:
        del request.session['id_entidade_altera']

    return render(request, "cadastro/entidade.html", context)

def altera(request, pk=None):
    print("altera")
    if pk:
        entidade = models.Entidade.objects.get(pk=pk)
        entidadesvinculadasPais = models.EntidadeVinculada.objects.filter(entidade_filha_id=entidade.id)
        entidadesvinculadasFilhas = models.EntidadeVinculada.objects.filter(entidade_propria_id=entidade.id)

        instance = get_object_or_404(models.Entidade, id=entidade.id)
        form_entidade = forms.EntidadeForm(request.POST or None, instance=instance)

        entidadespais = functions.get_entidades_pais(entidade.tipo_entidade.id)



        context = {
            'form_entidade': form_entidade,
            'entidade': entidade,
            'entidadesvinculadasPais': entidadesvinculadasPais,
            'entidadesvinculadasFilhas': entidadesvinculadasFilhas,
            'entidade_active': True,
            'listTipoProcesso': models.TipoProcesso.objects.all,
            'list_estados_ibge': models.EstadoIbge.objects.all,
            'list_mun_ibge': models.MunicipioIbge.objects.all,
            'tipo_formulario': "altera",
            'list_tipo_pessoa': models.TipoPessoa.objects.all,
            'entidadespais': entidadespais,
            'situacoes': models.Situacao.objects.all,
        }

        request.session['id_entidade_altera'] = pk

        return render(request, "cadastro/entidade.html", context)
    else:
        entidade = None

    context = {
        'entidade': entidade
    }

    return render(request, "cadastro/entidade.html", context)



def detalhes(request, pk=None):
    if pk:
        entidade = models.Entidade.objects.get(pk=pk)
        entidadesvinculadasPais = models.EntidadeVinculada.objects.filter(entidade_filha_id=entidade.id)
        entidadesvinculadasFilhas = models.EntidadeVinculada.objects.filter(entidade_propria_id=entidade.id)

        context = {
            'entidade': entidade,
            'entidadesvinculadasPais': entidadesvinculadasPais,
            'entidadesvinculadasFilhas': entidadesvinculadasFilhas,
        }

        return render(request, "cadastro/detalhes.html", context)



def ajax(request):
    if request.GET.get('action') == 'load_mun':
        id_estado_ibge = request.GET.get('estado_ibge')

        listmunicipios = models.MunicipioIbge.objects.filter(estado_ibge__id=id_estado_ibge).order_by('descricao_mun_ibge')

        context = {
            'municipios': listmunicipios,
        }
        return render(request, "cadastro/ajax/municipios_list.html", context)

    if request.GET.get('action') == 'get_processo':
        nroprocesso = request.GET.get('processo')
        listprocessos = models.Sei.objects.filter(nro_processo=nroprocesso)

        if listprocessos.count() > 0:  #len(listprocessos)
            sei = listprocessos[0]

            context = {
                'id_tipo_processo': sei.tipo_processo.id,
                'descricao_processo': sei.descricao,
            }
            return JsonResponse(context)


    if request.GET.get('action') == 'get_endereco':
        cep = request.GET.get('cep')
        url = "https://viacep.com.br/ws/"+cep+"/json/"

        try:
            response = urllib.request.urlopen(url)
            data = json.loads(response.read())
        except:
            return HttpResponse()

        return JsonResponse(data)

    if request.GET.get('action') == 'novo_endereco':
        if 'id_entidade_endereco' in request.session:
            del request.session['id_entidade_endereco']

        formEndereco = forms.EnderecoForm(request.POST or None)
        formMun = forms.MunicipioForm(request.POST or None)
        formEntEnd = forms.EntidadeEnderecoForm(request.POST or None)

        context = {
            'form_endereco': formEndereco,
            'form_mun': formMun,
            'form_ent_end': formEntEnd,
        }
        return render(request, "cadastro/ajax/form_endereco.html", context)


    if request.GET.get('action') == 'altera_endereco':
        id_ee = request.GET.get('id_entidade_endereco')
        entidadeendereco = models.EntidadeEndereco.objects.get(pk=id_ee)
        entidadeendereco.tipo_endereco = request.GET.get('tipo_endereco')
        entidadeendereco.endereco.bairro = request.GET.get('bairro')
        entidadeendereco.endereco.cep = request.GET.get('cep')
        entidadeendereco.endereco.logradouro = request.GET.get('logradouro')
        entidadeendereco.endereco.numero = request.GET.get('numero')
        entidadeendereco.endereco.complemento = request.GET.get('complemento')
        entidadeendereco.endereco.latitude = request.GET.get('latitude')
        entidadeendereco.endereco.longitude = request.GET.get('longitude')
        entidadeendereco.endereco.municipio_ibge = models.MunicipioIbge.objects.get(pk=request.GET.get('municipio'))
        entidadeendereco.save()
        entidadeendereco.endereco.save()

        return HttpResponse()

    if request.GET.get('action') == 'exclui_endereco':
        id_entidade_endereco = request.GET.get('id_entidade_endereco')
        entidadeendereco = models.EntidadeEndereco.objects.get(pk=id_entidade_endereco)
        entidadeendereco.dt_extincao = date.today()
        entidadeendereco.save()
        return  HttpResponse()


  # ===================================================================
    if request.GET.get('action') == 'get_pessoa':
        cpfpessoa = request.GET.get('cpfpessoa')
        # idtipopessoa = request.GET.get('id_tipo_pessoa')

        listpessoas = models.PessoaFisica.objects.filter(cpf_pessoa=cpfpessoa)
        # listpessoas = listpessoas.filter(tipo_pessoa = models.TipoPessoa.objects.get(pk=idtipopessoa))

        if listpessoas.count() > 0:  # len(listprocessos)
            pessoafisica = listpessoas[0]
            context = {
                # 'id_tipo_pessoa': pessoafisica.tipo_pessoa.id,
                'nome_pessoa': pessoafisica.nome_pessoa,
            }
            return JsonResponse(context)


    if request.GET.get('action') == 'nova_pessoa':
        if 'id_entidade_pessoa' in request.session:
            del request.session['id_entidade_pessoa']

        formPessoa = forms.PessoaForm(request.POST or None)
        formEntPessoa = forms.EntidadePessoaForm(request.POST or None)

        context = {
            'form_pessoa': formPessoa,
            'form_ent_pessoa': formEntPessoa,
        }
        return render(request, "cadastro/ajax/form_pessoa.html", context)


    if request.GET.get('action') == 'altera_pessoa':
        id_ep = request.GET.get('id_entidade_pessoa')
        entidadepessoa = models.EntidadePessoa.objects.get(pk=id_ep)
        entidadepessoa.telefone_pessoa = request.GET.get('telefone')
        entidadepessoa.email_pessoa = request.GET.get('email')
        entidadepessoa.pessoa.cpf_pessoa = request.GET.get('cpf')
        entidadepessoa.pessoa.nome_pessoa = request.GET.get('nome')
        entidadepessoa.pessoa.tipo_pessoa = models.TipoPessoa.objects.get(pk=request.GET.get('id_tipo_pessoa'))
        entidadepessoa.save()
        entidadepessoa.pessoa.save()

        return HttpResponse();

    if request.GET.get('action') == 'exclui_pessoa':
        id_entidade_pessoa = request.GET.get('id_entidade_pessoa')
        entidadepessoa = models.EntidadePessoa.objects.get(pk=id_entidade_pessoa)
        entidadepessoa.dt_extincao = date.today()
        entidadepessoa.save()
        return  HttpResponse()



    #======================PROCESSOS=================================

    if request.GET.get('action') == 'novo_processo':
        form_sei = forms.SeiForm(request.POST or None)
        context = {
            'form_sei': form_sei,
        }
        return render(request, "cadastro/ajax/form_processo.html", context)

    if request.GET.get('action') == 'exclui_processo':
        id_sei = request.GET.get('id_sei')
        id_entidade = request.GET.get('id_entidade')

        entidade = models.Entidade.objects.get(pk=id_entidade)
        sei = models.Sei.objects.get(pk=id_sei)
        entidade.sei_set.remove(sei)


        return  HttpResponse()
#================================== VINCULAÇÃO ===============================
    if request.GET.get('action') == 'exclui_vinculacao':
        id_ev = request.GET.get('id_entidade_vinculada')
        entidadevinculada = models.EntidadeVinculada.objects.get(pk=id_ev)
        entidadevinculada.dt_extincao = date.today()
        entidadevinculada.save()

        return  HttpResponse()

    if request.GET.get('action') == 'altera_vinculacao':
        id_ev = request.GET.get('id_entidade_vinculada')
        entidadevinculada = models.EntidadeVinculada.objects.get(pk=id_ev)

cadastro/templates/cadastro/nova_entidade.html
{% extends 'app.html' %}

{% load static %}

{% block navbar-breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'entidade/home' %}">Cadastro</a>
</li>
<li class="breadcrumb-item">
    <a href="">{{ page_title }}</a>
</li>
{% endblock %}

{% block container %}

<form method="POST" id="entidadeForm" ajax-url="{% url 'ajax' %}">
    {% csrf_token %}

    <div class="row">
        <div id="cadastro-tabs" class="offset-3 col-6">
            <ul id="form-cadastro-steps" class="nav nav-steps">
                <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#entidade">
                        <span class="nav-label">Entidade</span>
                        <div class="nav-step"></div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#enderecos">
                        <span class="nav-label">Endereços</span>
                        <div class="nav-step"></div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="tab_representantes" data-toggle="tab" href="#representantes">
                        <span class="nav-label">Representantes</span>
                        <div class="nav-step"></div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="tab_agrs" data-toggle="tab" href="#agrs">
                        <span class="nav-label">AGRs</span>
                        <div class="nav-step"></div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#processos">
                        <span class="nav-label">Processos</span>
                        <div class="nav-step"></div>
                    </a>
                </li>
            </ul>
            <div id="form-cadastro-content" class="tab-content">
                <div class="tab-pane fade show active" id="entidade">
                    <div class="form-row justify-content-around">
                        {% include 'form.html' with form=form_entidade %}
                        {% include 'form.html' with form=form_ent_vin %}
                        {% include 'form.html' with form=form_ent_vin_sit %}
                    </div>
                    <div class="form-actions row justify-content-around">
                        <div class="col-md-5"></div>
                        <div class="col-md-5 d-flex justify-content-end">
                            <a href="#enderecos" data-toggle="tab" class="tab-next btn btn-primary">Avançar</a>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="enderecos">
                    <div class="form-row justify-content-around">
                        <div class="form-group col-md-4">
                          <label for="id_estado_ibge">UF</label>
                          <select class="form-control" id="id_estado_ibge">
                              <option value="0">----------</option>
                              {% for e in list_estados_ibge %}
                              <option value="{{ e.id }}">{{ e }}</option>
                              {% endfor %}
                          </select>
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_municipio_ibge">Cidade</label>
                          <select class="form-control" id="id_municipio_ibge">
                              <option value="0">----------</option>
                              {% for m in list_mun_ibge %}
                                  <option value="{{ m.id }}">{{ m }}</option>
                              {% endfor %}
                          </select>
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_cep">CEP</label>
                          <input type="text" name="cep" class="form-control cep" id="id_cep" onchange="">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_logradouro">Logradouro</label>
                          <input type="text" name="logradouro" class="form-control logradouro" id="id_logradouro">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_bairro">Bairro</label>
                          <input type="text" name="bairro" class="form-control bairro" id="id_bairro">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_numero">Número</label>
                          <input type="text" name="numero" class="form-control numero" id="id_numero">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_complemento">Complemento</label>
                          <input type="text" name="complemento" class="form-control complemento" id="id_complemento">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_latitude">Latitude</label>
                          <input type="text" name="latitude" class="form-control latitude" id="id_latitude">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_longitude">Longitude</label>
                          <input type="text" name="longitude" class="form-control longitude" id="id_longitude">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_tipo_endereco">Tipo endereço</label>
                          <input type="text" name="tipo_endereco" class="form-control tipo_endereco" id="id_tipo_endereco">
                        </div>
                        <div class="form-group col-md-4">
                          <label for="id_dt_criacao">Data criação</label>
                          <input type="text" name="dt_criacao" class="form-control dt_criacao" id="id_dt_criacao">
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div id="listenderecos">
                            <table id="table-listenderecos" class="table table-striped">
                              <tr>
                                <td>Teste</td>
                                <td>outro tete</td>
                              </tr>
                              <tr>
                                <td>Teste</td>
                                <td>outro tete</td>
                              </tr>
                            </table>
                        </div>
                      </div>
                    </div>
                    <div class="form-actions row justify-content-around mb-5">
                        <div class="col-md-5"></div>
                        <div class="col-md-5 d-flex justify-content-end">
                            <input type="button" value="Adicionar endereço" id="novoendereco" class="btn btn-primary">
                        </div>
                    </div>
                    <div class="form-actions row justify-content-around">
                        <div class="col-md-5"></div>
                        <div class="col-md-5 d-flex justify-content-end">
                            <a href="#entidade" data-toggle="tab" class="tab-prev btn btn-primary">Voltar</a>
                            <a href="#pessoafisica" data-toggle="tab" class="tab-next btn btn-primary">Avançar</a>
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade" id="representantes">
                    <div id="listpessoas">
                        <table id="table-listpessoas" class="table table-striped">
                        </table>
                    </div>
                    <input type="text" name="cpf" class="cpf" placeholder="CPF" id="id_cpf_rep" onchange="">
                    <input type="text" name="nome" class="nome" placeholder="Nome" id="id_nome_rep">
                    <input type="text" name="telefone" class="telefone" placeholder="Telefone">
                    <input type="text" name="email" class="email" placeholder="Email">
                    <input type="button" value="Adiciona Representante" id="novorep"
                           onclick="btn_click('representantes')">


                </div>
                <div class="tab-pane fade" id="agrs">
                    <div id="listpessoas">
                        <table id="table-listpessoas" class="table table-striped">
                        </table>
                    </div>
                    <input type="text" name="cpf" class="cpf" placeholder="CPF">
                    <input type="text" name="nome" class="nome" placeholder="Nome">
                    <input type="text" name="telefone" class="telefone" placeholder="Telefone">
                    <input type="text" name="email" class="email" placeholder="Email">
                    <input type="button" value="Adiciona AGR" id="novoagr" onclick="btn_click('agrs')">
                </div>

                <div class="tab-pane fade" id="processos">
                    <div id="listprocessos">
                        <table id="table-listprocessos" class="table table-striped">
                        </table>
                    </div>

                    <input type="text" name="nro_processo" placeholder="Nro processo" maxlength="255"
                           id="id_nro_processo"><br/>
                    <select id="id_tipo_processo">
                        <option value="0">----------</option>
                        {% for p in listTipoProcesso %}
                        <option value="{{ p.id }}">{{ p.descricao_processo }}</option>
                        {% endfor %}
                    </select>
                    <br/>
                    <textarea rows="4" cols="50" id="id_descricao">
                    </textarea>
                    <br/><br/><br/>
                    <input type="button" value="Adiciona Processo" id="novoprocesso">
                    <!--                        {% include 'form.html' with form=form_sei %}-->
                </div>
            </div>
            <input class="btn btn-primary" type="submit" value="Salvar" id="novaentidade">
        </div>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"/>


{% endblock %}

{% block custom_js %}
<script src="{% static 'js/cadastro_forms.js' %}"></script>
<script src="{% static 'js/jquery.tabletojson.js' %}"></script>
{% endblock %}